# W1-2作业：
## 使用Hardhat部署修改后的Counter
增加了一个add方法，代码详见counterV2文件夹，部署成功[交易地址](https://ropsten.etherscan.io/tx/0xf5ba6271ee575128e22b713f0192cab1406658c3a25a44b123899e63ffad56dd)
❌~~但是部署过程的状态输出不对，还在寻找问题所在,hardhat本地网络部署没有问题~~
![error](media/16458761030216/error.png)
本地部署时log输出正常，当部署到测试网时，部署脚本输出的状态不正确
以下列代码为例，
```javascript
counter默认是0，
console.log("counter before add 10", (await counter.counter()).toString());
await counter.add(10);
console.log("counter after add 10", (await counter.counter()).toString());
```
两个log打印的都是0
想了想应该是counter()函数是读取API服务器本地的状态值，add()还在交易队列,也就是add()方法并不会阻塞到交易真正进入区块
同理，deploy()方也是如此
不过想了想测试代码也不会写在这里，所以也没什么问题。~~应该是看到实例代码在部署这里输出了一些账户信息，所以脑子发热在这里加了些测试代码~~
后续通过下面代码直接查看测试网counter状态确实是符合预期
```javascript
const Web3 = require("web3")
let web3 = new Web3(new Web3.providers.HttpProvider("https://eth-ropsten.alchemyapi.io/v2/xxx"));
//合约地址
let conctractAddr = "0x987ac907a8e9d043190c45bf4a42119c30da8967"
web3.eth.getStorageAt(conctractAddr, 0).then(function(result) {
    console.log(result);
    console.log(web3.utils.hexToNumberString(result));
}).catch(function(err) {
    console.log(err)
});
```
## 使用Hardhat测试Counter
测试成功，代码详见counterV2文件夹![测试](media/16458761030216/test.png)
## 写一个脚本调用count()
```javascript
const {ethers, network} = require("hardhat");
const CONSTRACT_INFO = require(`../deployments/${network.name}/Counter.json`)
async function main() {
    let [owner] = await ethers.getSigners();
    let counter = await ethers.getContractAt("Counter",CONSTRACT_INFO.address,owner);
    await counter.count();
    console.log((await counter.counter()).toString());
}
main()
    .then(() => process.exit(0))
    .catch(error => {
        console.error(error);
        process.exit(1);
    });
```